@echo off
chcp 65001 >nul
echo 🚀 Starting development environment...

echo 📦 Starting Redis...
docker-compose up -d redis

echo 📦 Installing dependencies with locked versions...
npm ci

echo 🚀 Starting server in development mode...
echo 📝 Server will be available at http://localhost:3000
npm run dev:server

echo 🧹 Shutting down Redis...
docker-compose down redis
